### PR TITLE
Stub router

### PR DESCRIPTION
**Pull request by lsnape**
I've tested the `AccountantRouter` and `TestRouter` in my SPA. Both appear to be working as I expect.

All files are now cljc, meaning I can now start kee-frame on the JVM! The following test now runs:

``` clojure
(ns sandi.re-frame.about-test
  (:require [clojure.test :refer [deftest is testing]]
            [day8.re-frame.test :as rf-test]
            [kee-frame.core :as kf]
            [kee-frame.router :as router]
            [kee-frame.state :as state]
            [re-frame.core :as rf]
            [sandi.routing :refer [ui-routes]]
            [sandi.about.handlers :as handlers]
            [sandi.about.subs :as subs]))

(defn navigate!
  [url]
  (router/navigate! @state/router url))

(rf/reg-fx
 :http-xhrio
 (fn [opts]
   ;; TODO: call server handler and dispatch response body
   (rf/dispatch [::handlers/fetch-sample-1 {:success true}])))

(deftest foo-test
  (kf/start! {:initial-db {}
              :routes ["/" (ui-routes)]})
  (let [sample (rf/subscribe [::subs/sample])]
    (rf-test/run-test-sync
     (navigate! (kf/path-for :about))
     (is (true? (:success @sample))))))
```
Navigating to the `/about` URL triggers the controller handlers to be called, which in turn dispatches an `http-xhrio` request, overridden above.

This increases test coverage to the re-frame subs and handlers, server-side handlers (though not implemented above), and routes. Even better, the tests are synchronous, making them _much_ easier to write.

I've kept the change as small as possible. You may think parts of it need a refactor, which of course I'm happy to do.

Cheers!

### CODE REVIEW

**Comment by ingesolvoll** [comment]
Excellent! I'll merge it and have a look

**Comment by ingesolvoll** [comment]
I would prefer less cljs/clj conditionals, so I changed the code to use an interop ns, one in cljs and one in clj. Check it out! Code looks great, will experiment with more tests like your test in the first comment here.

**Comment by ingesolvoll** [comment]
I don't understand the url argument to the TestRouter constructor?

**Comment by lsnape** [comment]
Great! Yes agreed, much cleaner having the implementations in separate files. However, it is conceivable that an instance of `TestRouter` could be used in Clojurescript, say, if you were running tests in a JS environment that doesn't support HTML5 history, e.g. a NodeJS backend. I suspect that this isn't going to be a common requirement, but you may want to support it - up to you!

The `url` arg was intended to initialise the router at a location other than `/`. On reflection I don't think passing it this is needed and can be removed, but I think `url` still needs to be tracked internally (assoc'd after navigation) so that `dispatch-current!` works correctly.

**Comment by ingesolvoll** [comment]
The priority short term is simple API combined with good regression testing for the framework itself. There's still work to be done there, these changes might help.

Thank you so much for this contribution! Please let me know if you have more ideas :)

**Pull request merged**
